# Generated by Django 6.0.2 on 2026-03-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_decription_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colour',
            new_name='color',
        ),
    ]
